<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);
ini_set('log_errors', 1);

require_once __DIR__ . '/includes/config.php';
require_once __DIR__ . '/includes/PdfGenerator.php';

// Simulate a minimal PDF generation like schedule.php does
$pdf = new PdfGenerator();

$pdf->setHeaderCallback(function($pdf) {
    $pdf->setFillColor(79, 70, 229);
    $pdf->rect(0, 0, $pdf->getPageWidth(), 45, 'F');
    $pdf->setFont('helvetica', 'bold', 18);
    $pdf->setTextColor(255, 255, 255);
    $pdf->text(20, 16, APP_NAME);
    $pdf->setFont('helvetica', '', 9);
    $pdf->text(20, 26, 'Student Course Schedule');
    $pdf->setFont('helvetica', '', 8);
    $pdf->text(20, 35, 'Generated: ' . date('F d, Y \a\t H:i'));
    $pdf->setFillColor(245, 158, 11);
    $pdf->rect(0, 45, $pdf->getPageWidth(), 2, 'F');
    $pdf->setY(55);
});

$pdf->setFooterCallback(function($pdf) {
    $y = $pdf->getPageHeight() - 15;
    $pdf->setFillColor(248, 250, 252);
    $pdf->rect(0, $y - 5, $pdf->getPageWidth(), 20, 'F');
    $pdf->setFont('helvetica', '', 7);
    $pdf->setTextColor(148, 163, 184);
    $pdf->text(20, $y, APP_NAME . ' - Course Schedule');
    $pdf->text($pdf->getPageWidth() - 20, $y, 'Page ' . $pdf->getPageNumber());
    $pdf->line(20, $y - 3, $pdf->getPageWidth() - 20, $y - 3);
});

$pdf->heading('WEEKLY CLASS SCHEDULE');
$pdf->spacer(3);

$pdf->setFillColor(241, 245, 249);
$pdf->rect($pdf->getMarginLeft(), $pdf->y, $pdf->getContentWidth(), 35, 'F');

$pdf->infoRow('Student:', 'John Doe');
$pdf->infoRow('Reg Number:', 'STU001');
$pdf->infoRow('Semester:', 'Semester 1');
$pdf->y += 8;

$pdf->subheading('COURSE DETAILS');
$pdf->spacer(3);

$headers = ['Code', 'Course Name', 'Credits', 'Lecturer'];
$rows = [
    ['CS101', 'Intro to CS', '3', 'Dr. Smith'],
    ['MATH201', 'Calculus II', '4', 'Dr. Jones'],
];
$pdf->drawTable($headers, $rows, [60, 180, 50, 150]);
$pdf->spacer(10);
$pdf->bodyText('This document is generated by La Lumiere School.');

ob_start();
$pdf->output('test_schedule.pdf');
$pdfContent = ob_get_clean();

file_put_contents(__DIR__ . '/test_schedule_output.pdf', $pdfContent);
echo "SUCCESS: PDF generated, " . strlen($pdfContent) . " bytes\n";
